groups:
- name: all
  jobs:
  - get-product-version
  - deploy
  - validation-test
- name: deploy
  jobs:
  - get-product-version
  - deploy
- name: validation 
  jobs:
  - validation-test

resources:
- name: concourse-deploy-gemfire
  type: git
  check_every: 1m
  source:
    uri: https://github.com/c0-ops/concourse-deploy-gemfire
    branch: master
- name: omg-cli
  type: github-release
  check_every: 1m
  source:
    user: enaml-ops
    repository: omg-cli
- name: p-gemfire-bosh-release 
  type: github-release
  check_every: 1m
  source:
    user: c0-ops
    repository: cf-gemfire-release
    access_token: {{github-token}}
- name: omg-product-bundle
  type: github-release
  check_every: 1m
  source:
    user: enaml-ops
    repository: omg-product-bundle
    access_token: {{github-token}}
- name: {{deployment-name}}
  type: bosh-deployment
  source:
    #ca_cert: {{bosh-cacert}}
    deployment: {{deployment-name}}
    target: {{bosh-url}}
    username: {{bosh-user}}
    password: {{bosh-pass}}
- name: stemcells
  type: pivnet
  source:
    api_token: {{pivnet_api_token}}
    product_slug: stemcells
    product_version: {{stemcell-version}}

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

jobs:
- name: get-product-version
  plan:
    - get: concourse-deploy-gemfire
    - get: omg-cli
      params:
        globs:
        - omg-linux
    - get: omg-product-bundle
      trigger: true
      params:
        globs:
        - p-gemfire-plugin-linux
    - task: get-product-version
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-gemfire/ci/tasks/get-version-from-plugin.sh
        params:
          PRODUCT_PLUGIN: {{product_plugin}}
          OUTPUT_DIR: versions
        inputs:
        - name: concourse-deploy-gemfire
        - name: omg-cli
        - name: omg-product-bundle
        outputs:
        - name: versions
          path: ""
#    - task: update-pipeline
#      config:
#        platform: linux
#        image_resource:
#          type: docker-image
#          source:
#            repository: virtmerlin/deploy-worker
#        run:
#          path: concourse-deploy-gemfire/ci/tasks/update-pipeline.sh
#        params:
#          PIPELINE_NAME: deploy-gemfire
#          CONCOURSE_URL: {{concourse-url}}
#          CONCOURSE_USER: {{concourse-user}}
#          CONCOURSE_PASS: {{concourse-pass}}
#        inputs:
#        - name: concourse-deploy-gemfire
#        - name: versions
#        outputs:
- name: deploy
  plan:
    - get: concourse-deploy-gemfire
    - get: omg-cli
      passed: [get-product-version]
      params:
        globs:
        - omg-linux
    - get: omg-product-bundle
      passed: [get-product-version]
      trigger: true
      params:
        globs:
        - p-gemfire-plugin-linux
    - get: stemcells
      trigger: true
      params:
        globs:
        - {{stemcell-cpi-glob}}
    - get: p-gemfire-bosh-release
      trigger: true
      params:
        globs:
        - GemFire-v1.0.2.tgz
    - task: generate-manifest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-gemfire/ci/tasks/generate-pivotal-gemfire-service-manifest.sh
        params:
          BOSH_CLIENT: {{bosh-user}}
          BOSH_CLIENT_SECRET: {{bosh-pass}}
          BOSH_URL: {{bosh-url}}
          BOSH_PORT: {{bosh-port}}
          BOSH_CACERT: {{bosh-cacert}}
          DEPLOYMENT_NAME: {{deployment-name}}
          PRODUCT_PLUGIN: {{product_plugin}}
          STEMCELL_VERSION: {{stemcell-version}}
          OUTPUT_DIR: manifest
          OMG_AZ: {{az-list}}
          OMG_NETWORK_NAME: {{network-name}}
          OMG_LOCATOR_STATIC_IP: {{locator-ip-list}}
          OMG_SERVER_STATIC_IP: {{server-ip-list}}
          OMG_GEMFIRE_LOCATOR_VM_SIZE: {{locator-vm-size}}
          OMG_GEMFIRE_SERVER_VM_SIZE: {{server-vm-size}}

        inputs:
        - name: concourse-deploy-gemfire
        - name: omg-cli
        - name: omg-product-bundle
        outputs:
        - name: manifest
          path: ""
    - put: {{deployment-name}}
      params:
        manifest: manifest/deployment.yml
        stemcells:
        - stemcells/bosh-stemcell*.tgz
        releases:
        - p-gemfire-bosh-release/*.tgz
- name: validation-test 
  plan:
    - get: concourse-deploy-gemfire
    - task: has-multi-az-redundancy-map
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-gemfire/ci/tasks/validate-multi-az-redundancy-map.sh
        params:
          OMG_LOCATOR_STATIC_IP: {{locator-ip-list}}
          PIVNET_TOKEN: {{pivnet_api_token}}
        inputs:
        - name: concourse-deploy-gemfire
          

